### ISSUE TITLE
Enhance parametric study

### ISSUE THREAD

**Issue by pkrull-ansys** [ansys/pyadditive#161]
### 📝 Description of the feature

These enhancements may create their own issues. This issue is used to keep track of the requests.

Parametric study enhancements:
- [ ] Redefine units for some columns in data frame. These would include the derived columns like build rate and energy density. The units should be commonly used units.
- [x] Update data frame after each simulation rather than after all simulations have completed - moved to #448 
- [ ] Save simulation results
- [x] Add iteration as parameter to `run_simulations()`, #193 
- [x] Add import of csv file #118 
- [ ] Change auto-generated simulation id to be more readable, `<type>_<count>`, e.g. `sb_00001`
- [x] Handle `nan` values for `_validate_microstructure_input` #309

**Comment by pkrull-ansys** [comment]
Remaining issues will be addressed as the need arises. Closing.
