### ISSUE TITLE
Technical review - continuation

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyadditive#58]
After merging #46 ...

- [x] Documentation technical review - #62 
- [x] Change package name from ``ansys-additive`` to ``ansys-additive-core`` - #63 
- [x] Making ansys-api-additive repo public (after review) - https://github.com/ansys-internal/ansys-api-additive/pull/22
- [x] #59
- [x] Migrating to ``ansys`` organization
- [x] Fixing links due to org change - #72
- [x] Implementing official license headers (using ansys/pre-commit-hook) - #73
